Repository CS-230-Group18/Jailscape, pull requests merged in 2019-11, with the labels that each got.

#14 Create the Entity class & Direction enum.
  src/com/group18/core/Direction.java
  src/com/group18/model/entity/Entity.java
Labels: enhancement

#28 Revert "Created LevelParser file."
  .idea/.gitignore
  .idea/gradle.xml
  src/com/group18/core/LevelParser.java
Labels: bug

#29 Updated Entity class to support serialization
  .idea/misc.xml
  src/com/group18/model/entity/Entity.java
Labels: bug

#32 Add MessageOfTheDayService
  .idea/ant.xml
  src/com/group18/Main.java
  src/com/group18/service/MessageOfTheDayService.java
Labels: enhancement

#33 Bug Fix for MessageOfTheDayService
  src/com/group18/service/MessageOfTheDayService.java
Labels: bug

#34 Updated MessageOfTheDayService class format
  src/com/group18/service/MessageOfTheDayService.java
Labels: enhancement

#35 Removed Test code in the class Main
  src/com/group18/Main.java
Labels: bug

#37 Updated a few bugs in MessageOfTheDay
  src/com/group18/service/MessageOfTheDayService.java
Labels: bug

#38 Bug fix involving Entity & Direction going missing
  .idea/ant.xml
  src/com/group18/core/Direction.java
  src/com/group18/model/entity/Entity.java
  src/com/group18/service/MessageOfTheDayService.java
Labels: bug

#39 Started implementation of Cell class
  src/com/group18/exception/InvalidMoveException.java
  src/com/group18/model/Coordinate.java
  src/com/group18/model/Direction.java
  src/com/group18/model/Level.java
  src/com/group18/model/cell/Cell.java
  src/com/group18/model/entity/Entity.java
  src/com/group18/service/MessageOfTheDayService.java
Labels: enhancement

#40 Started Implementation of Ground Cell
  .idea/ant.xml
  src/com/group18/exception/InvalidMoveException.java
  src/com/group18/model/Coordinate.java
  src/com/group18/model/Direction.java
  src/com/group18/model/Level.java
  src/com/group18/model/cell/Cell.java
  src/com/group18/model/cell/Ground.java
  src/com/group18/model/cell/Wall.java
  src/com/group18/model/entity/Enemy.java
  src/com/group18/model/entity/Entity.java
  src/com/group18/model/entity/User.java
  src/com/group18/service/MessageOfTheDayService.java
Labels: enhancement

#42 Started implementing Ground cell
  src/com/group18/exception/InvalidMoveException.java
  src/com/group18/model/cell/Cell.java
  src/com/group18/model/cell/Ground.java
  src/com/group18/model/cell/Wall.java
  src/com/group18/model/entity/Enemy.java
  src/com/group18/model/entity/User.java
Labels: enhancement

#44 Updated Cell class - bug with checking if there was a certain entity …
  src/com/group18/model/cell/Cell.java
Labels: bug

#45 Implemented Wall cell
  src/com/group18/model/cell/Cell.java
  src/com/group18/model/cell/Wall.java
Labels: enhancement

#46 Updated the Cell hierarchy and removed Repository's
  src/com/group18/model/cell/Cell.java
  src/com/group18/model/cell/Ground.java
  src/com/group18/model/cell/Wall.java
  src/com/group18/repository/CellRepository.java
  src/com/group18/repository/EntityRepository.java
  src/com/group18/repository/Repository.java
Labels: bug, enhancement

#47 Implementing User class.
  .classpath
  .gitignore
  .idea/gradle.xml
  .idea/workspace.xml
  .project
  src/com/group18/model/Collectable.java
  src/com/group18/model/entity/User.java
Labels: enhancement

#48 Implemented enums
  .idea/workspace.xml
Labels: enhancement

#49 Added some initial assets.
  src/resources/assets/DoorBlack_128x.png
  src/resources/assets/DoorBlack_256x.png
  src/resources/assets/DoorBlack_64x.png
  src/resources/assets/DoorRed_128x.png
  src/resources/assets/DoorRed_256x.png
  src/resources/assets/DoorRed_64x.png
  src/resources/assets/DoorYellow_128x.png
  src/resources/assets/DoorYellow_256x.png
  src/resources/assets/DoorYellow_64x.png
  src/resources/assets/GroundCell_128x.png
  src/resources/assets/GroundCell_256x.png
  src/resources/assets/GroundCell_64x.png
  src/resources/assets/PlayerStand_128x.png
  src/resources/assets/PlayerStand_256x.png
  src/resources/assets/PlayerStand_64x.png
  src/resources/assets/PlayerWalk_128x.png
  src/resources/assets/PlayerWalk_256x.png
  src/resources/assets/PlayerWalk_64x.png
  src/resources/assets/WallCell_128x.png
  src/resources/assets/WallCell_256x.png
  src/resources/assets/WallCell_64x.png
  src/resources/assets/credits.txt
Labels: enhancement

#50 Updated various classes
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/workspace.xml
  src/com/group18/model/Actionable.java
  src/com/group18/model/Collectable.java
  src/com/group18/model/Colour.java
  src/com/group18/model/Coordinate.java
  src/com/group18/model/cell/Cell.java
  src/com/group18/model/cell/Ground.java
  src/com/group18/model/cell/Wall.java
  src/com/group18/model/entity/User.java
  src/com/group18/service/MessageOfTheDayService.java
Labels: bug

#51 Added file with link to preview animations.
  src/resources/assets/player_animations.txt
Labels: question

#55 Started implementation of Level and various Enemies
  .idea/workspace.xml
  src/com/group18/exception/InvalidDirectionException.java
  src/com/group18/model/Colour.java
  src/com/group18/model/Direction.java
  src/com/group18/model/ElementType.java
  src/com/group18/model/Level.java
  src/com/group18/model/cell/Cell.java
  src/com/group18/model/cell/Door.java
  src/com/group18/model/cell/Element.java
  src/com/group18/model/cell/Ground.java
  src/com/group18/model/cell/TokenDoor.java
  src/com/group18/model/entity/Enemy.java
  src/com/group18/model/entity/Entity.java
  src/com/group18/model/entity/StraightLineEnemy.java
  src/com/group18/model/entity/User.java
  src/com/group18/model/entity/WallFollowingEnemy.java
  src/com/group18/model/item/Collectable.java
  src/com/group18/model/item/ElementItem.java
  src/com/group18/model/item/Key.java
Labels: enhancement

#56 Updated MessageOfTheDayService
  .idea/workspace.xml
  src/com/group18/model/entity/StraightLineEnemy.java
  src/com/group18/model/entity/WallFollowingEnemy.java
  src/com/group18/service/MessageOfTheDayService.java
Labels: bug

#57 Implemented DumbTargetingEnemy
  .idea/workspace.xml
  src/com/group18/model/entity/DumbTargetingEnemy.java
Labels: enhancement

#58 Updated WallFollowingEnemy
  .idea/workspace.xml
  src/com/group18/model/Level.java
  src/com/group18/model/entity/DumbTargetingEnemy.java
  src/com/group18/model/entity/SmartTargetingEnemy.java
  src/com/group18/model/entity/WallFollowingEnemy.java
Labels: bug

#59 Updated various classes
  .idea/workspace.xml
  src/com/group18/model/Level.java
  src/com/group18/model/entity/WallFollowingEnemy.java
Labels: bug

#61 Coloured Door class
  .idea/workspace.xml
  src/com/group18/model/cell/ColourDoor.java
Labels: enhancement

#62 Implemented door interface class.
  .idea/workspace.xml
  src/com/group18/model/entity/Door.java
Labels: enhancement

#65 Frontend
  .idea/ant.xml
  .idea/workspace.xml
  src/com/group18/Main.java
  src/com/group18/controller/CreateUserMenuController.java
  src/com/group18/controller/HighScoreMenuController.java
  src/com/group18/controller/LevelsMenuController.java
  src/com/group18/controller/MainMenuController.java
  src/com/group18/controller/MenuController.java
  src/com/group18/controller/UserSelectionController.java
  src/com/group18/core/AddUserName.java
  src/com/group18/core/DeleteUserFromFile.java
  src/com/group18/core/FileReader.java
  src/com/group18/core/LevelParser.java
  src/resources/CreateUserMenu.fxml
  src/resources/HighScoreMenu.fxml
  src/resources/LevelsMenu.fxml
  src/resources/MainMenu.fxml
  src/resources/Top3HighScores.txt
  src/resources/UserNames.txt
  src/resources/UserSelectionMenu.fxml
Labels: enhancement

#69 Added two missing door assets.
  src/resources/assets/DoorBlue.png
  src/resources/assets/DoorGreen.png
Labels: enhancement

#70 Implemented SmartTargetingEnemy
  .idea/ant.xml
  .idea/workspace.xml
  src/com/group18/Main.java
  src/com/group18/algorithm/Graph.java
  src/com/group18/algorithm/Node.java
  src/com/group18/algorithm/RouteNode.java
  src/com/group18/core/UserRepository.java
  src/com/group18/exception/ShortestPathNotFoundException.java
  src/com/group18/model/Colour.java
  src/com/group18/model/Level.java
  src/com/group18/model/cell/Cell.java
  src/com/group18/model/entity/SmartTargetingEnemy.java
  src/com/group18/model/item/Key.java
Labels: enhancement

#81 Handling errors in Loader classes
  src/com/group18/core/Alert.java
  src/com/group18/core/DeleteUserFromFile.java
  src/com/group18/core/LevelLoader.java
  src/com/group18/core/UserRepository.java
  src/com/group18/model/cell/Teleporter.java
Labels: bug

#83 Started implementing movement phase on graphics end
  src/com/group18/controller/GameController.java
  src/com/group18/core/LevelLoader.java
  src/com/group18/model/cell/Cell.java
  src/com/group18/model/entity/Entity.java
  src/resources/levels/Level1.txt
Labels: enhancement

#84 Added animations & cleaned up code in the Game Controller
  src/com/group18/Main.java
  src/com/group18/controller/GameController.java
  src/com/group18/core/CreateLevelLayout.java
  src/com/group18/viewmodel/UserViewModel.java
Labels: enhancement

#87 Personal to Main
  src/resources/assets/Enemy/Basic/EnemyHatBlue.png
  src/resources/assets/Enemy/Basic/EnemyHatGreen.png
  src/resources/assets/Enemy/Basic/EnemyHatRed.png
  src/resources/assets/Enemy/Basic/EnemyHatYellow.png
  src/resources/assets/Enemy/Basic/FemaleEnemyIdle.png
  src/resources/assets/Enemy/Basic/FemaleEnemyWalk.png
  src/resources/assets/Enemy/Basic/MaleEnemyIdle.png
  src/resources/assets/Enemy/Basic/MaleEnemyWalk.png
  src/resources/assets/Enemy/DumbEnemyIdle.png
  src/resources/assets/Enemy/DumbEnemyWalk.png
  src/resources/assets/Enemy/EnemyHat.png
  src/resources/assets/Enemy/EnemyIdle.png
  src/resources/assets/Enemy/EnemyWalk.png
  src/resources/assets/Enemy/SmartEnemyIdle.png
  src/resources/assets/Enemy/SmartEnemyWalk.png
  src/resources/assets/Enemy/StraightEnemyIdle.png
  src/resources/assets/Enemy/StraightEnemyWalk.png
  src/resources/assets/Enemy/WallEnemyIdle.png
  src/resources/assets/Enemy/WallEnemyWalk.png
  src/resources/assets/Item/FireBoots.png
  src/resources/assets/Item/Flippers.png
  src/resources/assets/Item/KeyBlue.png
  src/resources/assets/Item/KeyGreen.png
  src/resources/assets/Item/KeyRed.png
  src/resources/assets/Item/KeyYellow.png
  src/resources/assets/Item/Token.gif
  src/resources/assets/credits.txt
Labels: enhancement

#88 Implemented new changes such as ResourceRepository, Pause Menu, Alert System
  src/com/group18/Main.java
  src/com/group18/controller/GameController.java
  src/com/group18/core/LevelLoader.java
  src/com/group18/core/LevelSaver.java
  src/com/group18/core/ResourceRepository.java
  src/com/group18/core/UserRepository.java
  src/com/group18/model/Level.java
  src/com/group18/model/State.java
  src/com/group18/model/entity/SmartTargetingEnemy.java
  src/com/group18/model/entity/WallFollowingEnemy.java
  src/com/group18/service/MessageOfTheDayService.java
  src/com/group18/viewmodel/UserViewModel.java
  src/resources/fonts/octin prison free.ttf
  src/resources/fonts/octin-prison-rg.otf
  src/resources/fonts/octin-prison-rg.ttf
Labels: enhancement
